name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[placement]
mode = "smart"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "995579.xyz"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "exmaple.com"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.keveon.io", custom_domain = true },
  { pattern = "quay.keveon.io", custom_domain = true },
  { pattern = "gcr.keveon.io", custom_domain = true },
  { pattern = "k8s-gcr.keveon.io", custom_domain = true },
  { pattern = "k8s.keveon.io", custom_domain = true },
  { pattern = "lscr.keveon.io", custom_domain = true },
  { pattern = "ghcr.keveon.io", custom_domain = true },
  { pattern = "cloudsmith.keveon.io", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.keveon.io", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
